# This is a basic workflow to help you get started with Actions

name: NewIssueTest

# Controls when the workflow will run
on:
  # Triggers theon creation of a new issue
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Perform the actions when a new issue is created.
      - uses: actions/checkout@v2
        with:
          repository: "dnnslmns/wow-support:main"
          path: "."
          token: ${{ secrets.GH_PAT }}
